version: '3'

services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - database:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: ./.docker/config/php/${PHP_VERSION}-fpm
            args:
                COMPOSER_VERSION: ${COMPOSER_VERSION}
                ENABLE_XDEBUG: ${ENABLE_XDEBUG}
                ENABLE_WKHTMLTOPDF: ${ENABLE_WKHTMLTOPDF}
                ENABLE_BLACKFIRE: ${ENABLE_BLACKFIRE}
        volumes:
            - ${APP_FOLDER}:/var/www
        #user: 1000:1000
    nginx:
        build:
            context: ./.docker/config/nginx
        volumes:
            - ${APP_FOLDER}:/var/www
            - ./.docker/config/nginx/nginx-${PROJECT_TYPE}.conf:/etc/templates/nginx.conf
        environment:
            ADMIN_FOLDER_PRESTASHOP: ${ADMIN_FOLDER_PRESTASHOP}
        depends_on:
            - php
        ports:
            - "80:80"
    mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025 # smtp server
          - 8025:8025 # web ui
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
            UPLOAD_LIMIT: 300M
    nodejs:
        image: "nikolaik/python-nodejs:latest"
        working_dir: /var/www/html/
        environment:
            - NODE_ENV=development
        volumes:
            - ./html:/var/www/html
        expose:
            - "8081"
        #command: bash -c "yarn install && yarn encore dev --watch"
volumes:
    database:
